In [2]:
import numpy as np

In [3]:
# Creating a 2x2 array
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [4]:
# Convert to NumPy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [5]:
import torch

In [6]:
# Convert to PyTorch Tensor
torch.Tensor(arr)

tensor([[ 1.,  2.],
        [ 3.,  4.]])

In [7]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [8]:
torch.ones((2, 2))

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [9]:
np.random.rand(2, 2)

array([[0.89009389, 0.09701757],
       [0.91763055, 0.51779196]])

In [10]:
torch.rand(2, 2)

tensor([[ 0.6041,  0.0548],
        [ 0.7925,  0.7723]])