# Matrix Basics

In [3]:
import numpy as np

In [4]:
# Creating a 2x2 array
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [5]:
# Convert to NumPy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [6]:
import torch

In [7]:
# Convert to PyTorch Tensor
torch.Tensor(arr)

tensor([[ 1.,  2.],
        [ 3.,  4.]])

In [8]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [9]:
torch.ones((2, 2))

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [10]:
np.random.rand(2, 2)

array([[0.37215104, 0.55442873],
       [0.93029731, 0.77391416]])

In [11]:
torch.rand(2, 2)

tensor([[ 0.5533,  0.7570],
        [ 0.7430,  0.3577]])

# Seed for Reproducibility

In [14]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [15]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [16]:
# No seed
np.random.rand(2, 2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [17]:
# No seed
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [20]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[ 0.4963,  0.7682],
        [ 0.0885,  0.1320]])

In [21]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[ 0.4963,  0.7682],
        [ 0.0885,  0.1320]])

In [22]:
# Torch No Seed
torch.rand(2, 2)

tensor([[ 0.3074,  0.6341],
        [ 0.4901,  0.8964]])

In [23]:
# Torch No Seed
torch.rand(2, 2)

tensor([[ 0.4556,  0.6323],
        [ 0.3489,  0.4017]])

In [24]:
torch.cuda.is_available()

False

In [25]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)