# Variables

In [1]:
import torch
from torch.autograd import Variable

In [2]:
a = Variable(torch.ones(2, 2), requires_grad=True)
a

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [3]:
# Not a variable
torch.ones(2, 3)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])

In [4]:
# Behaves similarly to tensors
b = Variable(torch.ones(2, 2), requires_grad=True)
print(a + b)
print(torch.add(a, b))

tensor([[ 2.,  2.],
        [ 2.,  2.]])
tensor([[ 2.,  2.],
        [ 2.,  2.]])


In [5]:
print(a * b)
print(torch.mul(a, b))

tensor([[ 1.,  1.],
        [ 1.,  1.]])
tensor([[ 1.,  1.],
        [ 1.,  1.]])
